---
title: "Final Project: Data Sources & Student Examples"
subtitle: "ECI 586 Intro to Learning Analytics"
author: "Dr. Shaun Kellogg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
format:
  html:
    toc: true
    toc-depth: 3
theme:
  light: simplex
  dark: cyborg
editor: visual
---

## Data Sources

### Education Data

-   NC School Report Cards (SRC): <https://www.dpi.nc.gov/data-reports/school-report-cards/school-report-card-resources-researchers>

-   Open University Learning Analytics dataset: [https://www.nature.com/articles/sdata2017171](https://www.nature.com/articles/sdata2017171https://www.nature.com/articles/sdata2017171)

-   Friday Institute MOOC-Ed Resource Utilization Data: <https://moodle-courses2122.wolfware.ncsu.edu/pluginfile.php/1246137/mod_forum/post/604814/FI-Hewlett%20MOOC-Ed%20Data%20%28Fall%202014%29-2.xlsx> ([Data Codebook](https://moodle-courses2122.wolfware.ncsu.edu/pluginfile.php/1246137/mod_forum/post/604814/MOOC-Ed%20Data%20Set%202%20Description.docx))

-   National Center for Education Statistics: <https://nces.ed.gov/datatools/>

-   University of Virginia Education Statistics, Data Sets, and Data Experts: <https://guides.lib.virginia.edu/statisticsdatasets>

-   Urban Institute Education Data Explorer: <https://educationdata.urban.org/data-explorer/>

### Text Data

-   [Race to the Top Online PD Survey](https://moodle-courses2122.wolfware.ncsu.edu/pluginfile.php/1246137/mod_forum/post/604814/opd_survey.csv) ([Data Description pg. 15](https://moodle-courses2122.wolfware.ncsu.edu/pluginfile.php/1246137/mod_forum/post/604814/0%20-%20OPD_Y1_FINAL_11_9_12%20copy.jpg))

-   [MOOC-Ed Discussion Forums](https://moodle-courses2122.wolfware.ncsu.edu/pluginfile.php/1246137/mod_forum/post/604814/ts_forum_data.csv): https://moodle-courses2122.wolfware.ncsu.edu/pluginfile.php/1246137/mod_forum/post/604814/ts_forum_data.csv

### Network Data

-   Social Network Analysis and Education data sets: <https://studysites.sagepub.com/carolan/study/resources.htm>

-   Massively Open Online Course for Educators (MOOC-Ed) network dataset: <https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZZH3UB>

## Student Data Products

### Slides

-   Academic Mental Health on Twitter: <https://jennhouchins.github.io/Sentiments/SentimentAnalysisinR.html#1>

-   North Carolina Goes Back to School: <https://cullerth.github.io/wk_7_indpndnt_analysis/wk_7_presentation.html#1>

### Reports

-   Comparing Duke, UNC, and NC State Twitter Activity: A Text Mining Approach: <https://sorayaworldwide.github.io/DukeUNCNCStateTweets.html>

### Case Studies

-   Predicting Non-success in a College Science Course: <https://rpubs.com/rmlucas/845863>

-   #BlackinSTEM and #DiversityinSTEM Twitter Analysis: <https://rpubs.com/dsc21/845881>

### Dashboards

-   Accountability and Testing Reports Dashboard: <https://jkhouchins.shinyapps.io/accountability/>

-   Troubles with Technology for School Children in America: <https://speckart.shinyapps.io/Project/>
