---
title: "Final Project: Independent Data Product"
subtitle: "ECI 586 Intro to Learning Analytics"
author: "Dr. Shaun Kellogg"
date: today
format:
  html:
    toc: true
    toc-depth: 3
theme:
  light: simplex
  dark: cyborg
editor: visual
---

## Overview

For the end-of-course project, you'll be applying the knowledge and skills gained throughout this semester to conduct the independent analysis proposed in the previous assignment. Similar to the case studies provided in this course, your analysis should demonstrate your ability to wrangle, analyze, and communicate findings in response to a research question of interest. You will also be expected to use [Quarto](https://quarto.org) (or [R Markdown](https://bookdown.org/yihui/rmarkdown/) if preferred) to create a reproducible data product (e.g., slide show, dashboard, report, mini "data product", etc.), which contains all the code used during each step of your analysis so it can be reproduced by others.

## Grading Criteria

Your final project is worth **18 points total**. You will receive **1 point (10 points total) for each of the project criteria adequately addressed** by your data product, and **4 points (8 points total) for each post providing constructive feedback** to at least two of your peers.

### Prepare

Your data product should demonstrate your ability to formulate clear, actionable research questions relevant to a targeted audience. Specifically, your data product should include an **introduction** that:

1.  Clearly describes the **purpose** of your data product, including the research question(s) guiding your analyses.

2.  Provides information about the **data sources**, including the context in which the data was collected and variables used to address your research questions.

### Wrangle

Your data project should demonstrate your ability to use R to manipulate, clean, transform, and/or merging data in order to prepare your data for analysis. Specifically, your data product should clearly describe:

3.  **Data preprocessing** steps (e.g., renaming variables, filtering, tokenization, stemming, dealing with missing values, etc.) taken to clean and prepare your data for analysis and why are they necessary, as well as any steps will excluded and why.

4.  Any **new variables or features** you created to address your research questions; or any data **transformations** you made required for the types of analyses or packages used (e.g. reshaping, merging, joining etc.).

### Analyze

Your data project should demonstrate your ability to use R to apply learning analytics techniques appropriate to your research questions and data sources. Specifically, your data product should clearly include:

5.  Clear descriptions of the **techniques** (e.g., descriptive statistics, network analysis, sentiment analysis, etc.) you applied to analyze your data.

6.  Interpretations/meanings of specific **metrics** (e.g., counts, means, proportions, sentiment values, centrality measures, etc.) that your analysis generated. 

7.  Data **visualizations** that are attractive and easy to interpret, and include text or narrative for aiding their Interpretation by others.

### Communication

Your data product should demonstrate your ability to clearly and effectively communicate the most important and most useful findings. Specifically, your data product should:

8.  Highlights **key finding and insights** in response to your research questions.

9.  Suggests potential **action** that you and/or your target audience to better understand and improve the context in which your data product is intended to inform.

10. Discusses the **limitations** and any ethical/legal issues taken into consideration, including acknowledgments any reference materials used.

## Example Student Projects

### Slides

1.  **Academic Mental Health on Twitter**\
    *By Jennifer Houchins*\
    This project explores public sentiment around academic mental health using Twitter data. Through sentiment analysis in R, the study investigates how users discuss mental health in academic contexts and identifies prevailing emotions and keywords across tweets.\
    URL: <https://jennhouchins.github.io/Sentiments/SentimentAnalysisinR.html#1>

2.  **North Carolina Goes Back to School**\
    *By Tori Culler*\
    This analysis focuses on public discourse during the reopening of North Carolina schools in the context of COVID-19. Using text mining techniques, the project examines Twitter conversations to understand concerns, emotions, and topics prevalent in the back-to-school dialogue.\
    URL: <https://cullerth.github.io/wk_7_indpndnt_analysis/wk_7_presentation.html>

### Reports

3.  **Comparing Duke, UNC, and NC State Twitter Activity: A Text Mining Approach**\
    *By Soraya Campbell.*\
    This report compares the social media presence of three major North Carolina universities by analyzing tweets mentioning Duke, UNC, and NC State. It employs frequency analysis, sentiment classification, and topic modeling to uncover differences in public perception and communication patterns.\
    URL: <https://sorayaworldwide.github.io/DukeUNCNCStateTweets.html>

### Case Studies

4.  **Predicting Non-success in a College Science Course**\
    *By Rebecca Lucas*\
    This case study applies text mining and predictive modeling to student responses from a college science course. The goal is to identify linguistic patterns that may signal academic struggle or risk of non-completion, offering insights for early intervention.\
    URL: <https://rpubs.com/rmlucas/845863>

5.  **#BlackinSTEM and #DiversityinSTEM Twitter Analysis**\
    *By Deijah Scales.*\
    This project analyzes Twitter discussions using the hashtags #BlackinSTEM and #DiversityinSTEM. It applies sentiment and topic analysis to highlight key themes, voices, and issues shared by users advocating for inclusion and equity in STEM fields.\
    URL: <https://rpubs.com/dsc21/845881>

6.  **Reddit Vaccine Myths Sentiment Analysis**\
    *by* Jessica Bethea\
    This project analyzes sentiment within the r/VaccineMyths subreddit to understand how users discuss and perceive vaccines, particularly in the context of misinformation. By examining trends over time, the study explores whether user sentiment aligns with the subreddit’s goal of dispelling vaccine myths and identifies periods of heightened discussion.\
    URL: <https://rpubs.com/jmbethe2/983173>
